name: (Develop) CI - On Pull Request

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      # - name: Running Lint
      #   run: yarn lint

      # - name: Running Tests
      #   run: yarn test

      - name: Building Application
        run: yarn build
